platform: linux

image_resource:
  type: docker-image
  source: 
    repository: ruby
    tag: 2.4.1

inputs:
- name: flight-school

run:
  #path: find
  #args: ['.']
  #path: ls
  #args: ["-l",  "./flight-school/ci/test.sh"]
  path: ./flight-school/ci/test.sh
